window.LESSON_DATA = {
  title: "Rivstart B2/C1 - Kapitel 1-3: ord och verb",
  creatorCredit: "Quizlet-set skapade av AnnaRansheim",
  disclaimer: "En oberoende studieanpassning. Inte officiellt material från Quizlet, Rivstart eller förlaget.",
  sets: [
    {
      id: "chapter1",
      title: "Så funkar ett språkgeni - Kapitel 1",
      sourceUrl: "https://quizlet.com/_8nlhmv",
      entries: [
        [1,"avslöjar (ngt FÖR ngn)","reveals","يكشف (شيئاً لشخص)"],
        [2,"utmaning-en (MED ngt FÖR ngn)","challenge","تحدٍّ"],
        [3,"bevisar","proves","يثبت"],
        [4,"uppdrag-et","mission; assignment","مهمة؛ تكليف"],
        [5,"utrustad","equipped","مُجهَّز"],
        [6,"gör sitt yttersta","does his/her utmost","يبذل قصارى جهده"],
        [7,"slukar","devours","يلتهم"],
        [8,"utförlig","detailed","مفصّل"],
        [9,"drygt","just over","أكثر بقليل من"],
        [10,"uppskattar","estimates","يقدّر"],
        [11,"enastående","outstanding; unique","استثنائي؛ متميز"],
        [12,"ytterligare","further; additional","إضافي؛ مزيد من"],
        [13,"begåvning-en","talent","موهبة"],
        [14,"ansträngning-en","effort","مجهود"],
        [15,"nämligen","namely","أي؛ تحديداً"],
        [16,"förknippar","associates","يربط؛ يقترن في ذهنه"],
        [17,"upplevelse-n","experience","تجربة"],
        [18,"snäv","narrow","ضيّق؛ محدود"],
        [19,"myndighet-en","public authority","جهة حكومية؛ سلطة"],
        [20,"egenskap-en","quality; characteristic","صفة؛ خاصية"],
        [21,"uteslutande","exclusively","حصرياً؛ فقط"],
        [22,"mönster (mönstret)","pattern","نمط"],
        [23,"tillvaro-n","existence; life","وجود؛ حياة"],
        [24,"verksam","active; working","نشِط؛ عامل"],
        [25,"föreläsare-n","lecturer","محاضر"],
        [26,"utarbetar","develops; elaborates","يُعِدّ؛ يطوّر بالتفصيل"],
        [27,"skiner upp","brightens up; looks happy","يشرق وجهه؛ يبدو سعيداً"],
        [28,"(syskon-)skara-n","group (of siblings)","مجموعة (من الإخوة)"],
        [29,"anfall-et","attack; seizure","نوبة؛ هجوم"],
        [30,"tillflykt-en","refuge","ملجأ"],
        [31,"färdighet-en","skill","مهارة"],
        [32,"anstränger sig","makes an effort","يبذل جهداً"],
        [33,"förmedlar","conveys","ينقل؛ يوصّل"],
        [34,"känslomässig","emotional","عاطفي"],
        [35,"gemenskap-en","community; fellowship","مجتمع؛ شعور بالانتماء"],
        [36,"utvecklar","develops","يطوّر"],
        [37,"kommer på","thinks of; realizes","يخطر بباله؛ يدرك"],
        [38,"meningsfull","meaningful","ذو معنى"],
        [39,"anmärkningsvärd","remarkable","لافت للنظر"],
        [40,"irrar runt","wanders around","يتجوّل تائهاً"],
        [41,"livnär sig","makes a living","يكسب رزقه"],
        [42,"inriktar sig (på)","focuses on","يركّز على"],
        [43,"omgivning-en","surroundings; people around you","المحيط؛ الأشخاص من حولك"],
        [44,"utlöser","triggers; sparks","يُطلِق؛ يسبّب"],
        [45,"uppmuntrar","encourages","يشجّع"],
        [46,"ställer upp","helps; supports","يساعد؛ يساند"],
        [47,"kartlägger","maps out","يرسم خريطة؛ يحصر ويدرس"],
        [48,"håller isär","keeps apart; distinguishes","يفصل بين؛ يميّز"],
        [49,"glosa-n","vocabulary word","مفردة؛ كلمة للحفظ"],
        [50,"kännetecken (kännetecknet)","characteristic; distinguishing feature","سمة مميّزة"],
        [51,"i hög grad","to a large extent","إلى حد كبير"],
        [52,"besitter","possesses","يمتلك"],
        [53,"behärskar","masters; has command of","يتقن"],
        [54,"avrundar","rounds off; concludes","يختتم؛ يقرّب الرقم"],
        [55,"kommer överens","agrees; gets along","يتفق؛ ينسجم"],
        [56,"underbarn-et","prodigy","طفل معجزة؛ نابغة"],
        [57,"ödmjuk","humble","متواضع"],
        [58,"främst","mainly; foremost","بشكل رئيسي؛ أولاً"],
        [59,"får utlopp för","finds an outlet for","يجد متنفساً لـ"],
        [60,"förtjusning-en","delight; excitement","بهجة؛ سرور"],
        [61,"i regel","as a rule; generally","عادةً؛ كقاعدة عامة"]
      ]
    },
    {
      id: "verbs1to3",
      title: "Verb - Kapitel 1-3",
      sourceUrl: "https://quizlet.com/_8n36aw",
      entries: [
        [1,"anar","has a feeling; suspects; anticipates","يشعر؛ يشتبه؛ يتوقع"],
        [2,"beror (PÅ ngt/ngn)","depends on","يعتمد على"],
        [3,"bryr sig (OM ngn/ngt)","cares about","يهتم بـ"],
        [4,"knäcker koden","cracks the code","يفك الشفرة"],
        [5,"kräver","demands; requires","يطلب؛ يتطلب"],
        [6,"lossnar","comes loose; comes off","ينفك؛ ينفصل"],
        [7,"når","reaches; attains","يصل؛ يحقق"],
        [8,"sker","happens; occurs","يحدث"],
        [9,"släpper","releases; lets go","يُطلِق؛ يترك"],
        [10,"smäller","slams; bangs","يصفق بقوة؛ يُحدث دوياً"],
        [11,"stöter","strikes; pokes; pushes","يصطدم؛ يدفع؛ ينكز"],
        [12,"upplever","experiences; feels","يختبر؛ يشعر"],
        [13,"uppskattar","appreciates; estimates","يقدّر؛ يُثمّن"],
        [14,"upptäcker","discovers; detects","يكتشف"],
        [15,"ägnar (sig/ngt ÅT ngn/ngt)","devotes; dedicates","يكرّس؛ يخصص"],
        [16,"anförtro (sig ÅT ngn)","confides; entrusts","يفضي بسرّه؛ يأتمن"],
        [17,"avskyr","hates; detests","يكره بشدة"],
        [18,"beter sig","behaves","يتصرّف"],
        [19,"flyr","escapes; flees","يهرب"],
        [20,"glor","stares; glares","يحدّق"],
        [21,"snor","twists; steals (informal)","يلوي؛ يسرق (عامية)"],
        [22,"spyr","vomits; throws up","يتقيأ"],
        [23,"strör","scatters; sprinkles","ينثر؛ يرش"],
        [24,"avviker, avvek, avvikit","differs; deviates","يختلف؛ ينحرف"],
        [25,"ber, bad, bett","asks; begs; prays","يطلب؛ يتوسل؛ يصلّي"],
        [26,"består, bestod, bestått (AV ngt)","consists of","يتكوّن من"],
        [27,"driver, drev, drivit","drives; runs; impels","يقود؛ يدير؛ يدفع"],
        [28,"knyter, knöt, knutit","ties; fastens","يربط؛ يعقد"],
        [29,"pågår, pågick, pågått","continues; lasts; is in progress","يستمر؛ يجري"],
        [30,"rinner, rann, runnit","flows; runs","يجري؛ يسيل"],
        [31,"sliter, slet, slitit","tears; pulls; works hard","يمزق؛ يكدح"],
        [32,"slår, slog, slagit","hits; strikes","يضرب"],
        [33,"sprider, spred, spridit","spreads","ينشر"],
        [34,"umgås, umgicks, umgåtts","socializes; spends time together","يتواصل اجتماعياً؛ يقضي وقتاً مع"],
        [35,"uppger, uppgav, uppgett (uppgivit)","states; provides information","يذكر؛ يفيد بمعلومة"],
        [36,"behåller, behöll, behållit","keeps; retains","يحتفظ بـ"],
        [37,"förhåller sig, förhöll sig, förhållit sig","relates to; takes an attitude","يتعامل مع؛ يتخذ موقفاً"],
        [38,"ger sig ut, gav sig ut, gett (givit) sig ut","sets out; goes out","ينطلق؛ يخرج"],
        [39,"undviker, undvek, undvikit","avoids","يتجنب"],
        [40,"utgår, utgick, utgått (FRÅN ngt)","starts from; assumes","ينطلق من؛ يفترض"],
        [41,"återupptar, återupptog, återupptagit","resumes; takes up again","يستأنف"],
        [42,"beställer","orders","يطلب"],
        [43,"brer","spreads; makes a sandwich","يدهن؛ يحضّر شطيرة"],
        [44,"flår","skins; flays","يسلخ"],
        [45,"fyller","fills","يملأ"],
        [46,"för, förde, fört","transports; conveys","ينقل"],
        [47,"stjäl, stal, stulit","steals","يسرق"],
        [48,"spricker, sprack, spruckit","cracks; splits; bursts","يتشقق؛ ينفجر"],
        [49,"styr, styrde, styrt","steers; directs","يوجّه؛ يقود"],
        [50,"stör, störde, stört","disturbs; interrupts","يزعج؛ يقاطع"],
        [51,"bär, bar, burit","carries; wears","يحمل؛ يرتدي"],
        [52,"dör, dog, dött","dies","يموت"],
        [53,"förblir, förblev, förblivit","remains; stays","يبقى"],
        [54,"hinner, hann, hunnit","has time to do something","يلحق؛ يتسع له الوقت"],
        [55,"lider, led, lidit","suffers; is in pain","يعاني؛ يتألم"],
        [56,"lägger, lade, lagt","puts; places","يضع"],
        [57,"ser, såg, sett","sees","يرى"],
        [58,"sjunker, sjönk, sjunkit","sinks; goes down","يغرق؛ ينخفض"],
        [59,"skär, skar, skurit","cuts","يقطع"],
        [60,"slipper, slapp, sluppit","does not have to; escapes","لا يضطر؛ ينجو"],
        [61,"säljer, sålde, sålt","sells","يبيع"],
        [62,"sätter, satte, satt","puts; places; seats","يضع؛ يُجلِس"]
      ]
    },
    {
      id: "ordOrdOrd",
      title: "Ord, ord, ord – Kapitel 1",
      sourceUrl: "https://quizlet.com/_8n3678",
      entries: [
        [1,"betecknar","stands for","يعني؛ يرمز إلى"],
        [2,"formulerar","expresses","يعبّر؛ يصوغ"],
        [3,"rådande","prevailing","سائد؛ رائج"],
        [4,"godtycklig","arbitrary","اعتباطي"],
        [5,"överenskommelse-n","agreement","اتفاق"],
        [6,"förknippar","associate","يربط؛ يقترن في ذهنه"],
        [7,"föreställning-en","idea; conception","فكرة؛ تصور"],
        [8,"belägg-et","support (for)","دليل؛ سند"],
        [9,"härmar","imitates","يقلّد"],
        [10,"djurläte-t","animal call","صوت حيوان"],
        [11,"beteckning-en","denomination","تسمية؛ دلالة"],
        [12,"upplever","experiences","يختبر؛ يشعر"],
        [13,"representerar","represent","يمثل"],
        [14,"uppmärksammar","notices","يلاحظ"],
        [15,"rörelse-n","movement","حركة"],
        [16,"nedsättande","disparaging","ازدرائي؛ تحقيري"],
        [17,"innebär","means","يعني؛ يتضمن"],
        [18,"påhittad","made up; fictitious","مختلَق؛ وهمي"],
        [19,"uppger","states","يذكر؛ يفيد"],
        [20,"klang-en","tone","نبرة؛ صوت"],
        [21,"jämförelse-n","comparison","مقارنة"],
        [22,"omvänt","vice versa","بالعكس"],
        [23,"skiljer sig (åt)","is distinguished from","يختلف عن"],
        [24,"uppsättning-en","set","مجموعة؛ تشكيلة"],
        [25,"nämner","mentions","يذكر"],
        [26,"tillåter","permits","يسمح"],
        [27,"uppvisar","show","يعرض؛ يُظهر"],
        [28,"oändlig","infinite","لا نهائي"]
      ]
    }
  ]
};
